# Assignment (Intro to TensorFlow in Python)
---
This assignment has been adapted from the course **Introduction to TensorFlow in Python** on DataCamp. *italicized text*

---
## Introduction to TensorFlow
---
Before we can build advanced models in TensorFlow 2.0, we'll learn how to define constants and variables, perform tensor addition and multiplication, and compute derivatives. 

---
### Defining data as constants
---
Let us begin by importing constant from tensorflow.

After we have imported constant, we will use it to transform a numpy array, `credit_numpy`, into a tensorflow constant, `credit_constant`. This array contains feature columns from a dataset on credit card holders (the entire dataset has been loaded below) and is previewed in the image below.

![alt text](https://assets.datacamp.com/production/repositories/3953/datasets/10c0da730973582584bc227f4bca4b5510d42c9f/default_features.jpg)

Note that tensorflow version 2.0 allows us to use data as either a numpy array or a tensorflow constant object. Using a constant will ensure that any operations performed with that object are done in tensorflow. 

In [0]:
import pandas as pd 

credit_card_holders = pd.read_csv('uci_credit_card.csv')
credit_card_holders.head()

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default.payment.next.month
0   1    20000.0    2  ...       0.0       0.0                           1
1   2   120000.0    2  ...       0.0    2000.0                           1
2   3    90000.0    2  ...    1000.0    5000.0                           0
3   4    50000.0    2  ...    1069.0    1000.0                           0
4   5    50000.0    1  ...     689.0     679.0                           0

[5 rows x 25 columns]

In [0]:
credit_numpy = credit_card_holders[["EDUCATION", "MARRIAGE", "AGE", "BILL_AMT1"]].to_numpy()
print(type(credit_numpy))
print('='*40)
print(credit_numpy)
print('='*40)
print(len(credit_numpy))

<class 'numpy.ndarray'>
[[ 2.0000e+00  1.0000e+00  2.4000e+01  3.9130e+03]
 [ 2.0000e+00  2.0000e+00  2.6000e+01  2.6820e+03]
 [ 2.0000e+00  2.0000e+00  3.4000e+01  2.9239e+04]
 ...
 [ 2.0000e+00  2.0000e+00  3.7000e+01  3.5650e+03]
 [ 3.0000e+00  1.0000e+00  4.1000e+01 -1.6450e+03]
 [ 2.0000e+00  1.0000e+00  4.6000e+01  4.7929e+04]]
30000


Insructions:

* Import the `constant` submodule from the tensorflow module.
* Convert the `credit_numpy` array into a `constant` object in tensorflow. Do not set the data type.

In [0]:
# Import constant from TensorFlow
import tensorflow as tf

# Convert the credit_numpy array into a tensorflow constant
credit_constant = tf.constant(credit_numpy)

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

The datatype is: <dtype: 'float64'>
The shape is: (30000, 4)


---
### Defining variables
---
Unlike a constant, a variable's value can be modified. This will be quite useful when we want to train a model by updating its parameters. Constants can't be used for this purpose, so variables are the natural choice.

Let's try defining and working with a variable. 

Instructions:

* Define a variable, `A1`, as the 1-dimensional tensor: `[1, 2, 3, 4]`.
* Print `A1`. Do not use the `.numpy()` method. What did this tell you?
* Apply `.numpy()` to `A1` and assign it to `B1`.
* Print `B1`. 

In [0]:
# from tensorflow import Variable

# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print(A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
[1 2 3 4]


---
### Performing element-wise multiplication
---
Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors.

In this exercise, we will perform element-wise multiplication, paying careful attention to the shape of the tensors we multiply. 

Instructions:

* Define the tensors `A1` and `A23` as constants. It has been done for you. 
* Set `B1` to be a tensor of ones with the same shape as `A1`.
Set `B23` to be a tensor of ones with the same shape as `A23`.
Set `C1` and `C23` equal to the element-wise products of `A1` and `B1`, and `A23` and `B23`, respectively.

In [0]:
from numpy import ones_like, multiply

# # Import constant from TensorFlow
# from tensorflow import constant

# Define tensors A1 and A23 as constants
A1 = tf.constant([1, 2, 3, 4])
A23 = tf.constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1))
print('C23: {}'.format(C23))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


---
### Making predictions with matrix multiplication
---
The process of training linear regression models will yield a vector of parameters that can be multiplied by the input data to generate predictions. In this exercise, we will use input data, features, and a target vector, bill, which are taken from the credit card dataset (loaded as `credit_card_holders`). 

The matrix of input data, features, contains two columns: education level and age. The target vector, bill, is the size of the credit card borrower's bill.

Since we have not trained the model, we will enter a guess for the values of the parameter vector, params. We will then use `matmul()` to perform matrix multiplication of features by params to generate predictions, `billpred`, which we will compare with bill. 

Instructions:

* Define features, params, and bill as constants. This has been done for you. 
* Compute the predicted value vector, `billpred`, by multiplying the input data, features, by the parameters, params. Use matrix multiplication, rather than the element-wise product.
* Define `error` as the targets, `bill`, minus the predicted values, `billpred.` 

In [0]:
from numpy import matmul

# Define features, params, and bill as constants
features = tf.constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = tf.constant([[1000], [150]])
bill = tf.constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


---
### Optimizing with gradients
---
We are given a loss function, $ y = x^2 $, which we want to minimize. We can do this by computing the slope using the `GradientTape()` operation at different values of $x$. If the slope is positive, we can decrease the loss by lowering $x$. If it is negative, we can decrease it by increasing $x$. This is how gradient descent works.

![alt text](https://assets.datacamp.com/production/repositories/3953/datasets/4a3d06616c28aed697d57914a26da3d831bac83c/gradient_plot.png)

In practice, we will use a high level tensorflow operation to perform gradient descent automatically. In this exercise, however, we will compute the slope at $x$ values of -1, 1, and 0. 


Instructions:

* Define $x$ as a variable with the initial value $x0$.
* Set the loss function, $y$, equal to $x$ multiplied by $x$. 
* Set the function to return the gradient of $y$ with respect to $x$. 

In [0]:
# https://www.tensorflow.org/api_docs/python/tf/GradientTape 

# from tensorflow import GradientTape, Variable

def compute_gradient(x0):
  	# Define x as a variable with an initial value of x0
	x = tf.Variable(x0)
	with tf.GradientTape() as gt:
		gt.watch(x)
        # Define y using the multiply operation
		y = multiply(x,x)
    # Return the gradient of y with respect to x
	return gt.gradient(y, x).numpy()

# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


---
## Linear models
---

---
### Setting the data type
---
In this exercise, we will both load data and set its type. 

Instructions:

* Import `numpy` and `tensorflow` under their standard aliases.
* Use a `numpy` array to set the tensor `price` (from `housing` data) to have a data type of 32-bit floating point number
* Use the `tensorflow` function `cast()` to set the tensor `waterfront` to have a Boolean data type.
* Print `price` and then `waterfront`. Did you notice any important differences?

In [9]:
housing = pd.read_csv('kc_house_data.csv')
housing.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [10]:
# Import numpy and tensorflow with their standard aliases
import numpy as np
import tensorflow as tf 

# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Print price and waterfront
print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)
