# **Building deep learning models with keras**
---
We'll use the Keras library to build deep learning models for both regression and classification. We'll learn about the Specify-Compile-Fit workflow. 

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/SudhakarKuma/Machine_Learning/master/DataCamp_Notes/15_Introduction-to-Deep-Learning-in-Python/Datasets/hourly_wages.csv')
df.describe()

wage_per_hour       union  ...  manufacturing  construction
count     534.000000  534.000000  ...     534.000000    534.000000
mean        9.024064    0.179775  ...       0.185393      0.044944
std         5.139097    0.384360  ...       0.388981      0.207375
min         1.000000    0.000000  ...       0.000000      0.000000
25%         5.250000    0.000000  ...       0.000000      0.000000
50%         7.780000    0.000000  ...       0.000000      0.000000
75%        11.250000    0.000000  ...       0.000000      0.000000
max        44.500000    1.000000  ...       1.000000      1.000000

[8 rows x 10 columns]

In [0]:
target = df['wage_per_hour'].to_numpy()
predictors = df.drop(['wage_per_hour'], axis = 1 ).to_numpy()

In [0]:
target.shape
type(target)
print(target)

[ 5.1   4.95  6.67  4.    7.5  13.07  4.45 19.47 13.28  8.75 11.35 11.5
  6.5   6.25 19.98  7.3   8.   22.2   3.65 20.55  5.71  7.    3.75  4.5
  9.56  5.75  9.36  6.5   3.35  4.75  8.9   4.    4.7   5.    9.25 10.67
  7.61 10.    7.5  12.2   3.35 11.   12.    4.85  4.3   6.   15.    4.85
  9.    6.36  9.15 11.    4.5   4.8   4.    5.5   8.4   6.75 10.    5.
  6.5  10.75  7.   11.43  4.    9.   13.   12.22  6.28  6.75  3.35 16.
  5.25  3.5   4.22  3.    4.   10.    5.   16.   13.98 13.26  6.1   3.75
  9.    9.45  5.5   8.93  6.25  9.75  6.73  7.78  2.85  3.35 19.98  8.5
  9.75 15.    8.   11.25 14.   10.    6.5   9.83 18.5  12.5  26.   14.
 10.5  11.   12.47 12.5  15.    6.    9.5   5.    3.75 12.57  6.88  5.5
  7.    4.5   6.5  12.    5.    6.5   6.8   8.75  3.75  4.5   6.    5.5
 13.    5.65  4.8   7.    5.25  3.35  8.5   6.    6.75  8.89 14.21 10.78
  8.9   7.5   4.5  11.25 13.45  6.    4.62 10.58  5.    8.2   6.25  8.5
 24.98 16.65  6.25  4.55 11.25 21.25 12.65  7.5  10.25  3.35 13

In [0]:
predictors.shape
type(predictors)
print(predictors)

[[ 0  8 21 ...  0  1  0]
 [ 0  9 42 ...  0  1  0]
 [ 0 12  1 ...  0  1  0]
 ...
 [ 1 17 25 ...  0  0  0]
 [ 1 12 13 ...  1  0  0]
 [ 0 16 33 ...  0  1  0]]


---
## Specifying a model 
---

In [0]:
# Import necessary modules
import keras
from keras.layers import Dense
from keras.models import Sequential

# Save the number of columns in predictors: n_cols
n_cols = predictors.shape[1]

# Set up the model: model
model = Sequential()

# Add the first layer
model.add(Dense(50, activation='relu', input_shape=(n_cols,)))

# Add the second layer
model.add(Dense(32, activation='relu'))

# Add the output layer
model.add(Dense(1))

---
## Compiling and fitting a model
---

In [0]:
# Compile the model
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Verify that model contains information from compiling
print("Loss function: " + model.loss)

Loss function: mean_squared_error


In [0]:
# Fit the model
model.fit(predictors, target)

Epoch 1/1
534/534 [==============================] - 0s 188us/step - loss: 131.0628
